import { Document, Page, Text, View, StyleSheet, Image, Font } from '@react-pdf/renderer';

// Registering a standard font for a cleaner look
const styles = StyleSheet.create({
  page: { 
    padding: 40, 
    backgroundColor: '#ffffff',
    fontFamily: 'Helvetica'
  },
  headerSection: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderBottom: '2pt solid #e2e8f0',
    paddingBottom: 20,
    marginBottom: 20,
  },
  logo: {
    width: 50,
    height: 50,
  },
  titleContainer: {
    textAlign: 'right',
  },
  mainTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#1e293b',
  },
  dateText: {
    fontSize: 10,
    color: '#64748b',
    marginTop: 4,
  },
  messageContainer: {
    marginBottom: 15,
    padding: 12,
    borderRadius: 8,
    borderLeft: '4pt solid #cbd5e1',
  },
  userMessage: {
    backgroundColor: '#f8fafc',
    borderLeftColor: '#2563eb', // Blue for User
  },
  aiMessage: {
    backgroundColor: '#ffffff',
    borderLeftColor: '#10b981', // Green for AI
    borderWidth: 1,
    borderColor: '#f1f5f9',
  },
  roleLabel: {
    fontSize: 9,
    fontWeight: 'bold',
    textTransform: 'uppercase',
    marginBottom: 4,
    color: '#475569',
  },
  content: {
    fontSize: 11,
    lineHeight: 1.5,
    color: '#334155',
  },
  footer: {
    position: 'absolute',
    bottom: 30,
    left: 40,
    right: 40,
    fontSize: 9,
    textAlign: 'center',
    color: '#94a3b8',
    borderTop: '1pt solid #f1f5f9',
    paddingTop: 10,
  }
});

export const ChatPDF = ({ messages, fileName }) => {
  const now = new Date();
  const formattedDate = now.toLocaleDateString('en-US', { 
    year: 'numeric', month: 'long', day: 'numeric' 
  });
  const formattedTime = now.toLocaleTimeString('en-US', { 
    hour: '2-digit', minute: '2-digit' 
  });

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        {/* Header with Logo and Info */}
        <View style={styles.headerSection}>
          {/* Replace src with a local PNG path or URL if logo.svg fails to render */}
          <Image 
            style={styles.logo} 
            src="/logo.svg" 
          />
          <View style={styles.titleContainer}>
            <Text style={styles.mainTitle}>Chat Transcript</Text>
            <Text style={styles.dateText}>{fileName || 'Document'}</Text>
            <Text style={styles.dateText}>{formattedDate} | {formattedTime}</Text>
          </View>
        </View>

        {/* Chat Content */}
        {messages.map((msg, i) => (
          <View 
            key={i} 
            style={[
              styles.messageContainer, 
              msg.role === 'user' ? styles.userMessage : styles.aiMessage
            ]}
          >
            <Text style={styles.roleLabel}>
              {msg.role === 'user' ? 'You' : 'AI Assistant'}
            </Text>
            <Text style={styles.content}>{msg.content}</Text>
          </View>
        ))}

        {/* Footer */}
        <Text style={styles.footer} render={({ pageNumber, totalPages }) => (
          `Generated by Gemini AI Helpdesk • Page ${pageNumber} of ${totalPages}`
        )} fixed />
      </Page>
    </Document>
  );
};